# Configuracion de la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/clorian_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=""
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Evita que Spring intente crear tablas automaticamente
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none

# verás más detalles en la consola.
logging.level.com.clorian.webhook=DEBUG

# línea que defina el contexto para que Spring Boot exponga los endpoints correctamente.
server.servlet.context-path=/









